---
# Configuration of the Cycloid stack
name: 'Prometheus'
canonical: 'stack-prometheus'
status: 'public'
description: |
  Deploy a standalone Prometheus stack with Docker components on Aws EC2 server.
  Contain Alertmanager, Grafana and Prometheus.
keywords:
  - 'prometheus'
  - 'provider:aws'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-prometheus/master/icon.png
technologies:
  - technology: Debian
    version: 9.x
  - technology: Nginx
    version: 1.1x
  - technology: docker
    version: n/a
  - technology: telegraf
    version: n/a
  - technology: grafana
    version: n/a
  - technology: alertmanager
    version: n/a
  - technology: prometheus
    version: n/a

config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of ansible for provisionning
  ansible:
    prometheus:
      path: 'ansible/environments/prometheus.yml.sample'
      destination: '($ project $)/ansible/environments/($ environment $)-prometheus.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    prometheus:
      path: 'terraform/prometheus.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/prometheus.tf'
